/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package chinesesegmentclient;

import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author zoo88115
 */
public class AutoRun extends javax.swing.JFrame {

    File files[] = null;

    /**
     * Creates new form AutoRun
     */
    public AutoRun() {
        initComponents();
        jTextArea1.setEditable(false);
        jTextArea2.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("執行");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, 40));

        jButton2.setText("選取檔案");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("細明體", 0, 24)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 750, 400));

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("新細明體", 0, 24)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 620, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setMultiSelectionEnabled(true);
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileFilter filter = new FileNameExtensionFilter("Text File", "txt");
        fc.addChoosableFileFilter(filter);//只選取txt檔

        int returnVal = fc.showDialog(this, "選取txt檔案");
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            files = fc.getSelectedFiles();
            String selectFilesName = "";
            int count = 0;
            for (File d : files) {
                if (count % 5 == 4) {
                    selectFilesName += "\n";
                }
                if (count % 5 == 0) {
                    selectFilesName += d.getName();
                } else {
                    selectFilesName += "," + d.getName();
                }
                count++;
            }
            jTextArea2.setText(selectFilesName);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SegChinese seg = new SegChinese();
        try {
            ArrayList<SegmentStatus> arrayList = new ArrayList<SegmentStatus>();
            ArrayList<SegmentStatus> StoreArrayList = new ArrayList<SegmentStatus>();
            ReadFile readFile = new ReadFile();//讀檔

            if (files != null) {
                jTextArea1.setText("");
                String temp = readFile.getFileString(files[0].getAbsolutePath());
                jTextArea1.append("目前讀取：" + files[0].getAbsolutePath() + "\n");
                StoreArrayList.clear();
                StoreArrayList = seg.getSegment(new String[]{temp});//第一次
                for (int i = 1; i < files.length; i++) {
                    //jTextArea1.update(jTextArea1.getGraphics());//刷新textArea
                    temp = readFile.getFileString(files[i].getAbsolutePath());
                    jTextArea1.append("目前讀取：" + files[i].getAbsolutePath() + "\n");
                    arrayList.clear();
                    arrayList = seg.getSegment(new String[]{temp});
                    Integrate(StoreArrayList, arrayList);
                    Collections.sort(StoreArrayList);
                }
                jTextArea1.setText(jTextArea1.getText() + "斷詞\t次數\t篇數" + "\n");
                for (SegmentStatus d : StoreArrayList) {
                    //jTextArea1.update(jTextArea1.getGraphics());//刷新textArea
                    jTextArea1.append(d.echoString() + "\n");
                }
                //=================JSONObject
                JSONObject jsonObject = new JSONObject();
                JSONArray jsonArray = new JSONArray();
                JSONArray columns=new JSONArray();
                jsonObject.put("title", "INSERT");//使用功能
                jsonObject.put("table","dictionary");//使用的table
                columns.put("keyword");columns.put("times");columns.put("piece");//欄位
                jsonObject.put("columns",columns);
                for (SegmentStatus d : StoreArrayList) {
                    jsonArray.put(d.echoJSONArray());
                }
                jsonObject.put("insert", jsonArray);//加入值陣列
                MySQL mysql=new MySQL("127.0.0.1","chinesesegment_dictionary","root","1234");
                mysql.decode(jsonObject);
                jTextArea1.append("Success");
                files = null;
                jTextArea2.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Unselected Archives");
            }

        } catch (Exception e) {
            jTextArea1.setText(jTextArea1.getText() + e.toString() + "\n");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void Integrate(ArrayList<SegmentStatus> oldArrayList, ArrayList<SegmentStatus> newArrayList) {
        for (SegmentStatus i : newArrayList) {
            int check = 0;
            for (SegmentStatus j : oldArrayList) {
                if (j.compareTo(i) == 0) {
                    check = 1;//已存在
                    j.setNewValue(i.time);
                    break;//後面不必再檢查，加快速度
                }
            }
            if (check != 1) {
                oldArrayList.add(i);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutoRun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutoRun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutoRun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutoRun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutoRun().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
